/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnimeEntry {
  id: bigint;
  title: string;
  description: string;
  thumbnailBlobId: string;
  videoBlobId: string;
}

export interface SiteSettings {
  siteName: string;
  logoUrl: string;
  heroBlobId: string;
  bgBlobId: string;
  bgType: string;
  bgColor: string;
}

export interface _SERVICE {
  addAnime: ActorMethod<[string, string, string, string], bigint>;
  updateAnime: ActorMethod<[bigint, string, string, string, string], boolean>;
  deleteAnime: ActorMethod<[bigint], boolean>;
  getAllAnime: ActorMethod<[], AnimeEntry[]>;
  getAnime: ActorMethod<[bigint], [AnimeEntry] | []>;
  updateSettings: ActorMethod<[string, string, string, string, string, string], undefined>;
  getSettings: ActorMethod<[], SiteSettings>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
