/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface backendInterface {
    addAnime(title: string, description: string, thumbnailBlobId: string, videoBlobId: string): Promise<bigint>;
    updateAnime(id: bigint, title: string, description: string, thumbnailBlobId: string, videoBlobId: string): Promise<boolean>;
    deleteAnime(id: bigint): Promise<boolean>;
    getAllAnime(): Promise<any[]>;
    getAnime(id: bigint): Promise<any>;
    updateSettings(siteName: string, logoUrl: string, heroBlobId: string, bgBlobId: string, bgType: string, bgColor: string): Promise<void>;
    getSettings(): Promise<any>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}

    async addAnime(title, description, thumbnailBlobId, videoBlobId) {
        try {
            return await this.actor.addAnime(title, description, thumbnailBlobId, videoBlobId);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }

    async updateAnime(id, title, description, thumbnailBlobId, videoBlobId) {
        try {
            return await this.actor.updateAnime(id, title, description, thumbnailBlobId, videoBlobId);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }

    async deleteAnime(id) {
        try {
            return await this.actor.deleteAnime(id);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }

    async getAllAnime() {
        try {
            return await this.actor.getAllAnime();
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }

    async getAnime(id) {
        try {
            return await this.actor.getAnime(id);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }

    async updateSettings(siteName, logoUrl, heroBlobId, bgBlobId, bgType, bgColor) {
        try {
            return await this.actor.updateSettings(siteName, logoUrl, heroBlobId, bgBlobId, bgType, bgColor);
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }

    async getSettings() {
        try {
            return await this.actor.getSettings();
        } catch(e) { if (this.processError) this.processError(e); throw e; }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
